### ISSUE TITLE
suggest pointing to a specific canari repo

### ISSUE THREAD

**Issue by secure411dotorg** [Bart-o-zz/ThreatRecon#3]
If you have a repeatable working way to install canari (other than only for ubuntu which I as I recall also doesn't work without messing around) that would be helpful if you also point to that.

I've certainly succeeded eventually at installing canari in the past - however canari seems unnecessary and not in active developement, docs / walk throughs don't work so I was happy to get rid of it. Following your instructions or theirs today on a new machine again leaves me going ... oh ... yeah... time wasting etc. So I'm sure it would be very helpful to others if you can point to the exact resources and working install instructions.

**Comment by heinbrian** [comment]
Hey @secure411dotorg I am running canari on OSX without issues (if you don't install Homebrew), it is actively maintained and works for many other transform developers and even more users - if you have issues with Canari please open a ticket with them
