### ISSUE TITLE
Transform Errors

### ISSUE THREAD

**Issue by JburkeRSAC** [Bart-o-zz/ThreatRecon#6]
I am attempting to run a domain Threat Recon and IP Threat Recon transform and receiving the following error:
![screen shot 2014-08-13 at 4 45 56 pm](https://cloud.githubusercontent.com/assets/4128479/3912546/371790a0-232c-11e4-912b-5057e4210848.png)

It looks like it's an error with Canari but I am not too sure

**Comment by Bart-o-zz** [comment]
Did you installed the module requests ?

http://docs.python-requests.org/en/latest/user/quickstart/#json-response-content

**Comment by JburkeRSAC** [comment]
Yes,

Here is a screenshot:

![screen shot 2014-08-13 at 5 05 52 pm](https://cloud.githubusercontent.com/assets/4128479/3912804/faab773c-232e-11e4-873b-295b82ca284c.png)

​This is running on an EC2 instance and I'd be willing to give you access
if need be for troubleshooting

**Comment by JburkeRSAC** [comment]
I apologize Bart this was a user error on my behalf.  I did not notice at the bottom of the console within Maltego it was stating that it was a permissions error on the /tmp directory for my current user.  The root user actually owned the /tmp directory so a quick $chown -R curr_user:user_group /tmp/ resolved the issue.

**Comment by Bart-o-zz** [comment]
okay no worries, i'm glad you solved it, the temp folder part in the script needs some work (same as the cache part etc)
