### ISSUE TITLE
No module named transforms.RootNodeToIndicator

### ISSUE THREAD

**Issue by brianwarehime** [Bart-o-zz/ThreatRecon#8]
I followed the instructions and imported the transforms and entity, however, when I add the Threat Recon entity to the graph, add a domain to it and run the Root Node to Indicator transform I get the following error:

![default](https://cloud.githubusercontent.com/assets/403903/4747074/e7b406ae-5a55-11e4-879d-1d36c2191b9d.png)

**Comment by heinbrian** [comment]
@brianwarehime I heard your issue is resolved? - please close if resolved
